# sudo mysql -u root -e "set persist protocol_compression_algorithms='zstd,uncompressed'"
# sudo mysql -u root -e "create database if not exists test;"
# sudo mysql -u root -e "create user 'test_user'@'127.0.0.1' identified WITH mysql_native_password BY '12345678';"
# sudo mysql -u root -e "CREATE USER 'sha2user'@'127.0.0.1' IDENTIFIED WITH caching_sha2_password BY '12345678';"
# sudo mysql -u root -e "grant all on *.* to 'test_user'@'127.0.0.1';"
# sudo mysql -u root -e "grant all on *.* to 'sha2user'@'127.0.0.1';"